### ISSUE TITLE
Unable to access the server

### ISSUE THREAD

**Issue by fpoirier1** [contentacms/contentajs#23]
Hello,

I am following the instruction to install the server and I am having a hard time to access the server. 

After cloning the repo, I created the config `local.yml` :

```
cms:
  host: http://headless.devel

cors:
  origin:
    - '*'
```

then I run `npm start`, I see `pm2` initializing but then when I hit `localhost:3000` in my browser I get the error message :

>This site can't be reached" 

I tried running `npm run debug` but no success there too.

What am I missing ?

Thanks for your help !
